"""Public pydantic schema layer. Every model the rest of the toolkit depends on."""

from __future__ import annotations

from pixel_forge.schemas.animation import (
    AnimationSpec,
    FrameSpec,
    ProceduralAnimationSpec,
)
from pixel_forge.schemas.asset import (
    AnimatedTileSpec,
    AssetDoc,
    AssetDocUnion,
    AssetHeader,
    AssetType,
    BaseAssetDoc,
    CharacterAsset,
    EnemyAsset,
    EnemyCombat,
    ExportOptions,
    PropAsset,
    SampleMap,
    SpriteAssetBase,
    TerrainAsset,
    TerrainSet,
    TileSpec,
    TransitionSpec,
    ValidationOptions,
    parse_asset_doc,
)
from pixel_forge.schemas.common import (
    RGBA,
    Anchor,
    BitmapShape,
    EllipseShape,
    LineShape,
    PixelShape,
    RectShape,
    Region,
    RegionTransform,
    Shape,
    ShapeBase,
    Vec2,
)
from pixel_forge.schemas.export_schemas import export_json_schemas
from pixel_forge.schemas.manifest import (
    AnimationKeyframe,
    AnimationPlayerExport,
    AnimationPlayerTrack,
    AssetManifest,
    AtlasRect,
    GodotAnimatedTileExport,
    GodotImportSettings,
    GodotManifest,
    GodotSampleMapExport,
    GodotTerrainSetExport,
    GodotTileCoord,
    GodotTileSetExport,
    SheetCellManifest,
    SheetManifest,
    SpriteFrameEntry,
    SpriteFramesAnimation,
    ValidationSummary,
)
from pixel_forge.schemas.palette import Palette, PaletteColor, PaletteRef
from pixel_forge.schemas.project import ProjectConfig
from pixel_forge.schemas.revision import (
    JSONScalar,
    JSONValue,
    OperationSpec,
    RevisionDiff,
    RevisionRecord,
)
from pixel_forge.schemas.source import ExternalSource, pin_key
from pixel_forge.schemas.style import ProvenanceEntry, StyleProfile
from pixel_forge.schemas.validation import Finding, Severity, ValidationReport

__all__ = [
    "RGBA",
    "Anchor",
    "AnimatedTileSpec",
    "AnimationKeyframe",
    "AnimationPlayerExport",
    "AnimationPlayerTrack",
    "AnimationSpec",
    "AssetDoc",
    "AssetDocUnion",
    "AssetHeader",
    "AssetManifest",
    "AssetType",
    "AtlasRect",
    "BaseAssetDoc",
    "BitmapShape",
    "CharacterAsset",
    "EllipseShape",
    "EnemyAsset",
    "EnemyCombat",
    "ExportOptions",
    "ExternalSource",
    "Finding",
    "FrameSpec",
    "GodotAnimatedTileExport",
    "GodotImportSettings",
    "GodotManifest",
    "GodotSampleMapExport",
    "GodotTerrainSetExport",
    "GodotTileCoord",
    "GodotTileSetExport",
    "JSONScalar",
    "JSONValue",
    "LineShape",
    "OperationSpec",
    "Palette",
    "PaletteColor",
    "PaletteRef",
    "PixelShape",
    "ProceduralAnimationSpec",
    "ProjectConfig",
    "PropAsset",
    "ProvenanceEntry",
    "RectShape",
    "Region",
    "RegionTransform",
    "RevisionDiff",
    "RevisionRecord",
    "SampleMap",
    "Severity",
    "Shape",
    "ShapeBase",
    "SheetCellManifest",
    "SheetManifest",
    "SpriteAssetBase",
    "SpriteFrameEntry",
    "SpriteFramesAnimation",
    "StyleProfile",
    "TerrainAsset",
    "TerrainSet",
    "TileSpec",
    "TransitionSpec",
    "ValidationOptions",
    "ValidationReport",
    "ValidationSummary",
    "Vec2",
    "export_json_schemas",
    "parse_asset_doc",
    "pin_key",
]
